# Frontend — Dev Environment Overrides
global:
  environment: dev
  namespace: cargotrack-dev
image:
  registry: "692828329130.dkr.ecr.us-east-1.amazonaws.com"
  tag: "a513a1cc4c7c0f6ce2537a0f08c6d54829979e28" # CI/CD overwrites on every push
  pullPolicy: Always
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuTargetPercent: 70
ingress:
  host: "dev.shopp-novaa.co.in"
