# Frontend — Prod Environment Overrides
global:
  environment: prod
  namespace: cargotrack-prod
image:
  registry: "692828329130.dkr.ecr.us-east-1.amazonaws.com"
  tag: "adcafb0a1ec2206923d0f9ec263b0b18a8a293d5" # CI/CD overwrites on every push
  pullPolicy: Always
replicas: 2
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuTargetPercent: 70
ingress:
  host: "shopp-novaa.co.in"
  annotations:
    alb.ingress.kubernetes.io/group.order: "20"
