# Frontend — Dev Environment Overrides
global:
  environment: dev
  namespace: cargotrack-dev
image:
  registry: "692828329130.dkr.ecr.us-east-1.amazonaws.com"
  tag: "88320aed1757eea276fa054397c165c50df4d54a" # CI/CD overwrites on every push
  pullPolicy: Always
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuTargetPercent: 70
ingress:
  host: "dev.shopp-novaa.co.in"
