# Frontend — Prod Environment Overrides
global:
  environment: prod
  namespace: cargotrack-prod
image:
  registry: "692828329130.dkr.ecr.us-east-1.amazonaws.com"
  tag: "a272bd3e9ad0adf6664a00b591b98fa7750237aa" # CI/CD overwrites on every push
  pullPolicy: Always
replicas: 3
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  cpuTargetPercent: 70
ingress:
  host: "shopp-novaa.co.in"
  annotations:
    alb.ingress.kubernetes.io/group.order: "20"
