# Frontend — Dev Environment Overrides
global:
  environment: dev
  namespace: cargotrack-dev
image:
  registry: "692828329130.dkr.ecr.us-east-1.amazonaws.com"
  tag: "de0004abcd6f590be2fd15cb225c7c44ef015a85" # CI/CD overwrites on every push
  pullPolicy: Always
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuTargetPercent: 70
