# Core Service — Dev Environment Overrides
global:
  environment: dev
  namespace: cargotrack-dev
image:
  registry: "692828329130.dkr.ecr.us-east-1.amazonaws.com"
  tag: "8df37e5c8805eed7054ca7d4b9284ae0e5593f03" # CI/CD overwrites on every push
  pullPolicy: Always
serviceAccount:
  roleArn: "arn:aws:iam::692828329130:role/cargotrack-irsa-core-service"
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuTargetPercent: 70
