# Document Service — Dev Environment Overrides
global:
  environment: dev
  namespace: cargotrack-dev
image:
  registry: "692828329130.dkr.ecr.us-east-1.amazonaws.com"
  tag: "4770f75916c6df0786337bc48ec02c2fdfa8dc91" # CI/CD overwrites on every push
  pullPolicy: Always
serviceAccount:
  roleArn: "arn:aws:iam::692828329130:role/cargotrack-irsa-document-service"
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuTargetPercent: 70
