# Document Service — Dev Environment Overrides
global:
  environment: dev
  namespace: cargotrack-dev
image:
  registry: "692828329130.dkr.ecr.us-east-1.amazonaws.com"
  tag: "ab06005d12b3b76c57e0700b4c3500342dee0aa3" # CI/CD overwrites on every push
  pullPolicy: Always
serviceAccount:
  roleArn: "arn:aws:iam::692828329130:role/cargotrack-irsa-document-service"
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuTargetPercent: 70
