# Document Service — Dev Environment Overrides
global:
  environment: dev
  namespace: cargotrack-dev
image:
  registry: "692828329130.dkr.ecr.us-east-1.amazonaws.com"
  tag: "21e511b7252252ec67f8d462170e76c9705f92ba" # CI/CD overwrites on every push
  pullPolicy: Always
serviceAccount:
  roleArn: "arn:aws:iam::692828329130:role/cargotrack-irsa-document-service"
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuTargetPercent: 70
